from pathlib import Path

#GIGACHAT_TOKEN = 'MDE5YjllYjAtNGNiZC03MzQ0LTkxNjYtNjY1MTlkZWM0NmRmOjk2YmY2YTlmLTBjNzUtNGI1YS05NzAyLWE2ZDEzZjA0NGE1YQ=='

GIGACHAT_TOKEN = 'MDE5YmMxMjEtMTUyNi03YjVhLTg5ZjUtM2U3M2RlYWM0NTlkOjFlYjI4NjA4LTQ0ZWQtNDkyYS04MDY1LTYxN2JiMmVkOWZiYQ==' #15/01/26

BASE_DIR = Path("C:\\PROJECT\\ai-agent")
DATA_DIR = BASE_DIR / "data"
FAISS_DIR = BASE_DIR / "faiss_index"
RAW_FILE = DATA_DIR / "raw.jsonl"
CHUNKS_FILE = DATA_DIR / "clean.jsonl"
RAW_OUTPUT = DATA_DIR / "raw.jsonl"





